### ISSUE TITLE
Editing Data and Exporting as XLSX

### ISSUE THREAD

**Issue by SheetJSDev** [RandomFractals/vscode-data-preview#123]
First off, this is very slick :)

Is it possible to open an XLSX file, edit values in the grid, and save back as XLSX?  The grid seems to be read-only.

PS: the snippet in https://github.com/RandomFractals/vscode-data-preview/blob/master/data/markdown/js-xlsx-file-formats.md is available at https://github.com/SheetJS/js-xlsx/blob/master/docbits/85_filetype.md

**Comment by RandomFractals** [comment]
@SheetJSDev thanks for your kind words. 

I do have a link to your docs in my readme.md: https://github.com/RandomFractals/vscode-data-preview#data-preivew--files-loading-details That extract was only for some md files testing.

At the moment, I don't plan to add data editing features in v1.x. Why I named this extension Data Preview. However, it's is possible with the grid library I am using, and I'll consider adding that feature in v2.x if more developers request it.

As for Save `.xlsx` files, I might add that feature soon. There is save `.csv` option already that you can use to load and save in Excel in other formats.

**Comment by RandomFractals** [comment]
@SheetJSDev let's do this for now: I'll add `.xlsx` export in the next major v. features update.

I'd like to hold off on grid data cells editing. that's like a few days of work I can't afford to swindle on my dime, but I like the idea! :)

**Comment by RandomFractals** [comment]
@SheetJSDev see code changes tagged above & in #127 + this pic for more info :) 

![vscode-data-preview-ods](https://user-images.githubusercontent.com/656833/62335008-9daa0880-b48f-11e9-8ae7-0091a31eb487.png)
