### ISSUE TITLE
preview of a file with windows 1252 encoding

### ISSUE THREAD

**Issue by intellekta** [RandomFractals/vscode-data-preview#131]
preview of a file with windows 1252 encoding
```
A;B;C;D;E;F;G;H
Ä;Ö;Ü;ä;ö;ü;ß;€
```
is wrong, it probably displays it in utf-8
```
A,B,C,D,E,F,G,H
ï¿½,ï¿½,ï¿½,ï¿½,ï¿½,ï¿½,ï¿½,ï¿½

```
thanks in advance

**Comment by RandomFractals** [comment]
yes, this extension assumes all text data files are utf-8 encoded and that will not change.

Please use other means to convert your input data to utf-8.
