### ISSUE TITLE
Preview Data on JSON file not showing anything

### ISSUE THREAD

**Issue by elliottyates** [RandomFractals/vscode-data-preview#158]
Not sure what should be happening here, but my status bar shows "Activating Extensions..." for a few moments, then nothing appears to happen at all in the IDE window. The Dev Tools show no messages. Can you recommend a way to get more helpful troubleshooting information? Thanks!

**Comment by RandomFractals** [comment]
@elliottyates try restarting vscode if you just install this extension and then some of the data files from this folder: https://github.com/RandomFractals/vscode-data-preview/tree/master/data/json

Also, please share vscode v. & OS you are on.

**Comment by elliottyates** [comment]
@RandomFractals thanks for your reply. I tried `cars.json` from the samples you provided, and it works fine. I think the issue is the JSON I'm trying to investigate -- it's a 4mb file. "Activating extension..." appears when I open it, then disappears after a few seconds. From that point forward, nothing happens, and subsequent attempts to open even small files, like `cars.json`, no longer do anything. So I imagine the extension is caught crunching the big file and isn't making it to any further operations.

I'm using VS Code 1.40.0 for what it's worth, on Mac OSX 10.14.6.

I guess I'll need a different approach to analyzing this large JSON file. Cheers!

**Comment by RandomFractals** [comment]
try converting it to csv. without you sharing your json data file I really can't help much.

I would run Data Preview on some other small json data file first. Once it's activated it should be availabe for other data file previews. 

So, then try loading your large json data file. I did test this ext. with large json & arrow data files on Win & while I saw vscode stall for some time for larger data files, just reading them from disk, I have not seen ext. activation fail.

It still doesn't sound right to me. Please share your data file if you'd like further assistance.

**Comment by RandomFractals** [comment]
also, are you sure it's not vscode failing to load your large json data file?

Uninstall Data Preview & try to load your json data file first for in code editor.

Does that work || is it too large for vscode to handle?

Do try converting it to csv.

**Comment by RandomFractals** [comment]
also, you don't have to open your json file to preview it with this extension.

Right click on your file in File Explorer & then click Preview Data. That should launch Data Preview and try to load your large json data.

However, you still have not told me if you even see Activated msgs in the status bar. so, ...

**Comment by elliottyates** [comment]
@RandomFractals:

- The activated message does show up in the status bar.
- I'm afraid I cannot share the original JSON data; I realize that's not very helpful.
- VS Code can display the file just fine, but tokenization is skipped because the character count is too high.
- Update: I do get an error eventually from the extension: `Unable to parse data file: '(filename)'. Error: Unexpected end of JSON input`. The data preview tab for this file does eventually open, with the final line in the window showing `> restoreConfig({})`. This JSON can be parsed by other python processes via the `json` library module, so I'm wondering if there's some issue with VS Code. There's another message originating from `JSON Language Features (Extension)`: `(filename): For performance reasons, document symbols have been limited to 5000 items.` I may try disabling this other extension to see if it helps Data Preview performance in any way.

Thanks!

**Comment by RandomFractals** [comment]
that's more helpful. have you tried loading my large data samples?

https://github.com/RandomFractals/vscode-data-preview/tree/master/data/large

let me know how they fair.

I did not just put loading large data files for preview in vscode for something, but I am sure there are limits on my & vscode end.

I do intend to add data streaming soon that should streamline that process drastically. just been busy with other things atm.

**Comment by elliottyates** [comment]
@RandomFractals I had not yet tried the large data samples. The 3.6mb JSON file loads fine, after about 15-20 seconds where it looks like nothing's happening. So perhaps there's something quirky about my 4mb file that's causing issues. Nice to hear about streaming. I'll keep my ear to the repo updates, and if I find out anything more I'll try to give you more info. I appreciate the help, suggestions, and your great work with the extension.

**Comment by RandomFractals** [comment]
cool. I'd do some more testing on larger OSS json data files later this week. still keeping this issue closed since while it's tantalizing I don't think we dove into deep enough to find a culprit and better resolution.

btw, I might be posting updates on this ext. in this dev.to post to make it more available for dev feedkback: https://dev.to/tarasnovak/visual-studio-code-data-preview-41no
