### ISSUE TITLE
add .ndjson and .jsonl support

### ISSUE THREAD

**Issue by universalmind303** [RandomFractals/vscode-data-preview#159]
A lot of people work with newline delimited json (ndjson) for logs, streaming, and a lot of other tools. 

It would be nice if this tool supported this format of json files.

**Comment by RandomFractals** [comment]
interesting. 1st time I heard of ndjson. btw, this extension already supports .hjson & .json5.

Adding ndjson would be just another json data provider: https://github.com/RandomFractals/vscode-data-preview/tree/master/src/data.providers

Can you link me to good ndjson parser to use and provide some examples of what systems/tools use it?

**Comment by universalmind303** [comment]
NDJson is commonly used in a lot tools that write to file in a stream. 
Apache Spark is an example of a tool that writes to ndjson. 
You also commonly see people that are writing logs to Elasticsearch format their logs into ndjson.

**Comment by RandomFractals** [comment]
ok. that's a compelling use case. I'll leave this open and will add it if other devs don't jump on it.

should be super easy to implement with the data providers API I have set up for parsing data files.

**Comment by RandomFractals** [comment]
JSON LInes spec: http://jsonlines.org/ & examples: http://jsonlines.org/examples/

**Comment by RandomFractals** [comment]
@universalmind303 so, this is done & done! I will push it out in the next release this week. Just testing and patching some perspective viewer JS updates ... see pic for those data formats display in data preview and tagged commits :) 

Also, feel free to pitch in with more info on ndjson format and usage in the wild in this dev.to discussion thread I started: https://dev.to/tarasnovak/who-uses-ndjson-h3a

![vscode-data-preview-ndjson](https://user-images.githubusercontent.com/656833/68871831-ab903c00-06c2-11ea-9e10-8721c88c8092.png)

**Comment by schlichtanders** [comment]
Just tested out this feature and was surprised that only ndjson, jsonl files are only supported on the load side, but not for save.

It would be very good to also have the option to **save** ndjson/jsonl file format. Or have I overlooked it?

**Comment by RandomFractals** [comment]
Not sure why are you surprised. You are the first person missing ndjosn/jsonl save feature.

Please open new feature request for that enhancement.

Thanks.
