### ISSUE TITLE
Feature-request: Generate plots directly from Variable explorer

### ISSUE THREAD

**Issue by hantusk** [RandomFractals/vscode-data-preview#164]
Vscode has gotten great jupyter notebook support. The interactive window has a "Variable explorer" which shows all variables in the globals() scope of Python. 

See https://code.visualstudio.com/docs/python/jupyter-support#_variable-explorer-and-data-viewer
It would be fantastic you could view plots of your data directly from there, instead having to export pandas dataframes to a proxy format.

**Comment by RandomFractals** [comment]
this might be a bit of topic.

I believe vscode already provides great support for Jupyter notebooks.

Data Preview main intent is to make it easy for devs to preview data files and provide basic filtering and charting features without Python skills or setup.

**Comment by hantusk** [comment]
That's cool, thanks for considering it :)
