### ISSUE TITLE
Icons Missing

### ISSUE THREAD

**Issue by sbuschjaeger** [RandomFractals/vscode-data-preview#165]
Hi,

I just installed Data Preview (Version: 1.49.0) and so far it works as expected. However, judging by the screenshots I have seen so far there seem to be missing some icons? 
Attached you can find a screenshot of my setup. 

My VS Code Version is 

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.11-arch1-1

![Screenshot from 2019-11-29 09-33-44](https://user-images.githubusercontent.com/32978972/69855541-03669f80-128c-11ea-8858-f9f361c89aca.png)

**Comment by RandomFractals** [comment]
@sbuschjaeger that's super odd. The 'icons' you are missing are utf-8 emojis.

I am not sure how to test or reproduce this. Do you have emojis show up in your vscode setup?

If so, you should see those 'icons' too :)
