### ISSUE TITLE
flatten nested object properties for json array data preview display

### ISSUE THREAD

**Issue by AiaRup** [RandomFractals/vscode-data-preview#168]
Hello,
I tried to view a JSON in the data-preview but it appears as [object object].

The raw data looks like this (mongo document):
![Screenshot 2019-12-02 at 13 04 30](https://user-images.githubusercontent.com/35365209/69960165-19cd5f00-1509-11ea-8623-738a556f6fbd.png)

When I preview only **one document** it looks like this as a preview:
![Screenshot 2019-12-02 at 13 04 51](https://user-images.githubusercontent.com/35365209/69960185-2356c700-1509-11ea-9f89-67bb998f9fbd.png)

When I want to look at **several documents** in a JSON file I see the [object object]:
![Screenshot 2019-12-02 at 13 06 09](https://user-images.githubusercontent.com/35365209/69960273-5436fc00-1509-11ea-8092-8ea3ede1cb44.png)

I don't know if it is a bug or I need to configure something?
Thank a lot!

**Comment by RandomFractals** [comment]
@AiaRup your first example is just a json config that is converted to flat properties list per this note in docs: https://github.com/RandomFractals/vscode-data-preview#data-preview--files-loading-details

Your 2nd example is most likely a json array. However, that json document has nested object properties for the _id and group properties & data preview doesn't try to expend them.

Perhaps, it could be improved for the latter use case.

**Comment by RandomFractals** [comment]
the only sensible solution for this use case I can propose and try to implement is flattening those objects, so that your json array grid with have the following headers:

`_id.$oid, resource, actions, grou.$oid`

this is due to the fact that json can be hierarchical, but we are display that data in a grid of rows and columnns, with is a flat 2 dimensional format :(

**Comment by AiaRup** [comment]
> the only sensible solution for this use case I can propose and try to implement is flattening those objects, so that your json array grid will have the following headers:
> 
> `_id.$oid, resource, actions, group.$oid`
> 
> this is due to the fact that json can be hierarchical, but we are displaying that data in a grid of rows and columns, which is a flat 2 dimensional format :(

It seems perfect, thanks a lot for all your hard work!

**Comment by RandomFractals** [comment]
btw, data preview also supports .jsonl format, if you just want to create a single json doc using concat.

see issue #159 for more info

**Comment by RandomFractals** [comment]
I am only bringing up jsonl since that and csv/tsv data formats will be the first to get data streaming implemented in the next v. update this month most likely.

With data streaming you'll be able to view hundreads of thousands of data rows. More info here: #167 

So, if you script your mongo db data dump that way, you'll be good to go and see more data loaded faster in the next data preview ext. update.

**Comment by RandomFractals** [comment]
@AiaRup btw, I also have mongoDB data connector penciled in for the data preview wish/todo list, but I don't think I'll get to it this year: #26 

Thumb it up & if I see more devs interested in that feature, I might move it up the implementation list :)

**Comment by AiaRup** [comment]
> I am only bringing up jsonl since that and csv/tsv data formats will be the first to get data streaming implemented in the next v. update this month most likely.
> 
> With data streaming you'll be able to view hundreds of thousands of data rows. More info here: #167
> 
> So, if you script your mongo db data dump that way, you'll be good to go and see more data loaded faster in the next data preview ext. update.

I will check it out, thank you so much!

**Comment by RandomFractals** [comment]
might try using json-2-csv for this prior to passing nested json objects to the grid view display which is tabular ...

https://github.com/mrodrig/json-2-csv

**Comment by RandomFractals** [comment]
actually, might try this json-spread lib instead: https://github.com/gone369/json-spread

**Comment by RandomFractals** [comment]
probably the best we can do to flatten json arrays with nested objects for now:

![image](https://user-images.githubusercontent.com/656833/94382210-7f768180-0101-11eb-9cec-9cec4ab9a1bb.png)
