### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by muhammadfazeel** [RandomFractals/vscode-data-preview#173]
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `1.49.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\KaShMiRi\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment]
this extension does a lot of heavy lifting, most of it via webassembly.

so, some of it is expected! :)

& there is not much we can do to improved, besides streaming data reads that I already have on my to do list.

**Comment by fajaede** [comment]
/Users/imac/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt   is added to home directory 
Build and Deploy failed github actions

**Comment by RandomFractals** [comment]
@fajaede that doesn't tell me anything. 

Also, I don't plan to debug generic vscode cpu profile reports due to various dev machine configurations.
