### ISSUE TITLE
cannot copy and paste cell content from data preview grid

### ISSUE THREAD

**Issue by gennaro-tedesco** [RandomFractals/vscode-data-preview#175]
I am running VSCode 1.41.1 on Mac OS Catalina 10.15.1

I would like to be able to copy entries of the data file from the preview interface (say, after filtering or sampling and so); apparently this feature is not in place (or am I wrong?), namely after selecting the text I want to copy, the copy functionality just does not appear to work. Is this as intended or am I doing it wrong (selecting text --> ctrl+c)?

**Comment by RandomFractals** [comment]
@gennaro-tedesco copy paste cells and rows is not implemented.

I'll look into it since I plan to update persepecive library I am using for the grid view to recently released v.0.4.0 soon.

**Comment by RandomFractals** [comment]
for the grid rows copy and paste, it's a question of how you'd like for it to function.

were would you like to paste selected rows from the grid and in what format? csv, json? ...

**Comment by gennaro-tedesco** [comment]
What I would like to do is very simple: while viewing a file content from the grid view (after say, filtering, selecting and so) I would like not necessarily to be able to copy the entire row, but even just the single cell content: your comment above states that it should be possible already, although it does not seem to work neither on a Mac nor on Ubuntu. The pasting is not really necessarily, the copying is what would be most useful (since I am jumping between different files and windows and I would need to quickly copy `ids` or indices).

**Comment by RandomFractals** [comment]
that sounds much simpler than I expected. I did ship alpha data grid edit feature in v1.47 of data preview. Can you make sure that's the version you have installed & I'll aks some dev friends to test copy cell content on those Linux platforms.

Also, new perspective lib v0.4.0 has been released recently and I plan to upgraded it in my extension soon. It features row selections too, but I have not wired it yet.

**Comment by RandomFractals** [comment]
@gennaro-tedesco I just had another dev try that on Ubuntu ...

![image](https://user-images.githubusercontent.com/656833/72627518-48b16000-3912-11ea-87ad-b5bfc098bf1d.png)

**Comment by gennaro-tedesco** [comment]
I do see the selection exactly as yours, however my problem is with the ctrl+c itself: it just doesn't seem to copy the text. Does it actually work in your case, namely are you able to copy and really paste elsewhere? In alternative, can one copy the text by selecting "copy" from some sort of dropdown menu or so?

In any case thank you very much for being responsive and looking into it.

**Comment by RandomFractals** [comment]
yes, confirmed that ctrl+c and paste in another grid cell or open vscode document works on Ubuntu.

**Comment by nice2m** [comment]
> I do see the selection exactly as yours, however my problem is with the ctrl+c itself: it just doesn't seem to copy the text. Does it actually work in your case, namely are you able to copy and really paste elsewhere? In alternative, can one copy the text by selecting "copy" from some sort of dropdown menu or so?
> 
> In any case thank you very much for being responsive and looking into it.

same here, copy and paste not work,

**Comment by texastoland** [comment]
Same on Mac and additionally no context menu to copy that way.
