### ISSUE TITLE
Please release also .vsix files

### ISSUE THREAD

**Issue by mirekphd** [RandomFractals/vscode-data-preview#176]
Most of VS Code extensions projects release also .vsix files (which are essentially zip, but still containing something other than just source code as in your case). Source code is of course fine, but separately from the .vsix extension file, like in this repo:
https://github.com/Azure/vscode-kubernetes-tools/releases

**Comment by RandomFractals** [comment]
why do you need .vsix files?

Most vscode extensions actually don't release .vsix files because they are just bundled versions of extension that you would only use if you decide to install an extension that is not in vscode marketplace.

**Comment by mirekphd** [comment]
I'm using containerised fully auto-updating installation of VS Code in an
air gapped cluster of corporate Linux servers (with sensitive customer
data). As an alternative for Jupyter Notebook / Lab for data scientists.
Broadens your mind beyond Windows 10 use case I suppose :)

**Comment by RandomFractals** [comment]
sure, why the snarky remark?

**Comment by RandomFractals** [comment]
@mirekphd I see you logged similar request for half a dozen of open source data related vscode extensions.

Here is a tip: see https://github.com/RandomFractals/vscode-data-preview#dev-build

& run `vsce package` to gen .vsix for the extensions you need for your containerized vscode installations.

**Comment by mirekphd** [comment]
It's a bit of an uphill struggle trying to standardise these assets on
GitHub that you guys prefer posting to the other Microsoft website :) Thank
you for the tip, I'll try out the vsce converter.

**Comment by RandomFractals** [comment]
it doesn't have to be. most devs install extensions from vscode or marketplace.

if you want to bundle and deploy them for your air gaped machines, follow the instructions I've provided. 

good luck!
