### ISSUE TITLE
Hide status bar item after launch

### ISSUE THREAD

**Issue by misolori** [RandomFractals/vscode-data-preview#185]
![image](https://user-images.githubusercontent.com/35271042/73287609-59819180-41ae-11ea-93bb-6283499445f7.png)

This is fine to show on launch and then go away after a few seconds. But I find it really annoying that this is always in the status bar. You already see the icon in the toolbar when you have a data file open so this feels very unnecessary. Any user can manually hide this in the status bar but I feel like this should be properly handled by the extension.

**Comment by RandomFractals** [comment]
@misolori I've done some work on this in v2.0.0 & ticket #183 

Please get the latest version! & thanks for your feedback!

**Comment by RandomFractals** [comment]
@misolori I am going to reopen this and do some more work on it soon.
