### ISSUE TITLE
setting preference to show/hide icons

### ISSUE THREAD

**Issue by rlodbrok** [RandomFractals/vscode-data-preview#188]
Hello,
i would like to see more enable/disable settings. Specifically the options to hide the always-present icon in the top-right toolbar.

At this point it does not seem possible to hide this. The bright orange icon is not aesthetically pleasing to me, and takes-up too space.

--thank you in advance.

**Comment by RandomFractals** [comment]
a few things:

1. That toolbar will most likely stay until better custom webview editor api is finalized for us to integrate it in this vscode extension.

see: https://github.com/microsoft/vscode/issues/77131

2. There is a good reason for that orange Data Preview emoji I picked.

You can read all about it here: https://twitter.com/TarasNovak/status/1220427189100929024

If you are referring to the icon I display for quick data preview of the supported data formats, I don't think it's possible to make it go away based on ext. settings.

**Comment by RobinTournemenne** [comment]
I add myself to the complaint of @rlodbrok . The reason to me is that I have constantly many files opened and that any space taken there is an annoyance to me. I don't use this button.

It is a very comon problem for vs code user: https://github.com/microsoft/vscode/issues/46403
(It is one of the top requested settings)

GitLens provides such a setting. It could be bery straightforward to copy the piece of code implementing this setting.

In any case, the dirty solution is to install customizeUI and add these two lines in your setting file:

```
"customizeUI.stylesheet": {
    ".editor-actions": "display: none !important;",
},
```

It will mess with the CSS used by VS Code and may break your previous config... (it broke my awesome synth84 theme)

**Comment by RandomFractals** [comment]
@rlodbrok this is still a wontfix. You can uninstall this extension if you don't use it.

Also, this extension doesn't use customizedUI styles and I have no intentions on switching to it.

Not sure what you mean by breaking your awesome synth84 theme.

Thanks for your feedback.

**Comment by RobinTournemenne** [comment]
My bad, re-reading my message, I want to apologize if you found any trace of bitterness. There was none. I think there was many misunderstanding.

> @rlodbrok this is still a wontfix. 

I am not the same user, I am @RobinTournemenne.

> You can uninstall this extension if you don't use it or it annoys you.

This is my bad, I thought that when opening a .xlsx file, it opened by default with your extension. Besides, I was rather surprised to see that the command "Data: Preview Data" called with a .xlsx file in the focused editor (for example) did not work and return the error "Open a Data file to Preview". I now understand that the only way to use your extension is to click on the orange icon.

> Also, this extension doesn't use customizedUI styles and I have no intentions of switching to it.

It was meant for @rlodbrok  to find a solution in the mean time. But given that the only solution to use your extension is this button it is kind of stupid to remove it.

> Not sure what you mean by breaking your awesome synth84 theme.

customizedUI messes with the CSS at the same time than the synth84 theme which, combined with a update of VS Code, breaks some things that I don't understand either.

> Thanks for your feedback.

np, thanks for your extension!

As I see it, one way to get this settings would be to have the "Data: Preview Data" works by itself (it should be the case): I mean that invoking the Command Palette when a data file is in the focused editor and typing "Data: Preview Data" should open your extension preview. or simply press ctrl + shift + D sohuld open it.
On the other side, we could add the setting removing the icon using the code of GitLens as an example.

Best regards,
Robin

**Comment by RandomFractals** [comment]
@RobinTournemenne no big deal on general comments. 

> As I see it, one way to get this settings would be to have the "Data: Preview Data" works by itself (it should be the case): I mean that invoking the Command Palette when a data file is in the focused editor and typing "Data: Preview Data" should open your extension preview. or simply press ctrl + shift + D sohuld open it.

As for the Data Preview commands, you should not need to open a data file to preview it. Data Preview adds context menu options to vscode explorer tree view, editor and title context menus & you can use the keyboard shortcut to launch it for an open data file. See Commands in my Installation doc section and Contributions pic :) https://github.com/RandomFractals/vscode-data-preview#installation

**Comment by RobinTournemenne** [comment]
> Data Preview adds context menu options to vscode explorer tree view, editor and title context menus 

Nice, I did not know it, so there are other possibilities to open your data preview extension!

> & you can use the keyboard shortcut to launch it for an open data file. 

As I said, the keyboard shortcut when I have a data file opened does not work for me; When I am trying, I get the error: "Open a Data file to Preview"
