### ISSUE TITLE
Can you please add an option to customize the font in the data preview?

### ISSUE THREAD

**Issue by alexzabbey** [RandomFractals/vscode-data-preview#190]
Would be really nice :)

**Comment by RandomFractals** [comment]
I think you should elaborate.

Current data preview ext. fonts & display are tight! :)

Try a light theme if your don't like our default dark ...

https://github.com/RandomFractals/vscode-data-preview#configuration

**Comment by alexzabbey** [comment]
The font in Hebrew isn't monospace, for instance, which makes it hard to read. If the font could be configurable like the fonts in the rest of VSCodeit would be nice and you wouldn't have to make additional changes for each language.
