### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by KyawMini** [RandomFractals/vscode-data-preview#191]
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.43.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\hp\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KyawMini** [comment]
C:\Users\hp\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt

**Comment by RandomFractals** [comment]
duplicate of #173 

see my comment there: https://github.com/RandomFractals/vscode-data-preview/issues/173#issuecomment-570789075
