### ISSUE TITLE
floating point numbers converted to integers

### ISSUE THREAD

**Issue by amalija-ramljak** [RandomFractals/vscode-data-preview#192]
The numeric values in a column are floored/rounded down when the first value in that column is an integer or .0 float with an arbitrary number of zeros.

Side by side .csv file and its preview, three numeric value columns
Val has 1.0 in the second row and is previewed as it should be - as floats (same if its just 1)
Val2 has 1.0 in the first row and is previewed as integers
Val3 has 1 in the first row and is previewed as integers
![image](https://user-images.githubusercontent.com/34318241/76665272-74a23800-6587-11ea-862c-46dc3398b490.png)

**Comment by JasonSwindle** [comment]
Just ran into this as well, but in Markdown:

| Time | Date       | Notes     |
|------|------------|-----------|
| 50   |            | blank |
| .5   | 2020-03-25 | blank  |

<img width="382" alt="image" src="https://user-images.githubusercontent.com/1776251/77576823-c5793100-6ea3-11ea-9006-d4d3f6854a11.png">

**Comment by RandomFractals** [comment]
yeah, this needs more work. more info here: #156
