### ISSUE TITLE
Sum column ?

### ISSUE THREAD

**Issue by JasonSwindle** [RandomFractals/vscode-data-preview#193]
Howdy,

I am *REALLY* loving what this tool can do, but I'm really hitting a wall on usability.   

I want to be able to sum the column __Time__, but I'm not able to figure this out, yet I see in the README.md this is a feature.

## Example Table
| Time | Date       | Notes                                                                               |
|------|------------|-------------------------------------------------------------------------------------|
| 2    | 2020-03-24 | Blah Blah Blah |
| 6    | 2020-03-24 |                                                                                     |
| 2    |            |                                                                                     |

**Comment by JasonSwindle** [comment]
Ok, I figured it how.  For people searching how to do this, here is how:

- Drag the column you with `Sum`  over to `Group By`
- Under the column you dragged, you will see a dropdown box
- Select `Sum`

<img width="339" alt="image" src="https://user-images.githubusercontent.com/1776251/77487260-061f6e80-6e00-11ea-950e-0d537fd02d39.png">

**Comment by RandomFractals** [comment]
yeah, just drag the column you want to run aggregate functions on to group by field :)
