### ISSUE TITLE
Extension breaks web.config and app.config highlighting.

### ISSUE THREAD

**Issue by zeeman4u** [RandomFractals/vscode-data-preview#195]
The extension types web.config and app.config are usually automatically opened as XML, but when this extension is installed, they get assigned to a .config type which does not highlight the syntax as the XML type does.

**Comment by RandomFractals** [comment]
sorry to hear that. I have a todo item to fix it already logged. see #155

**Comment by judwhite** [comment]
@RandomFractals I don't think this is a duplicate of #155, or I'm not reading the other issue correctly. This one I understand.

![data-preview-extension-breaks-config-xml](https://user-images.githubusercontent.com/729716/98561283-a13a5b00-22a0-11eb-9fa1-303b2785fe4a.png)
