### ISSUE TITLE
Monospace font

### ISSUE THREAD

**Issue by mhkeller** [RandomFractals/vscode-data-preview#196]
It would be nice if you had the option of making the data preview show up in a monospace font. It makes it easy to see if your columns are equal length or if you have any weird aberrations.

**Comment by mhkeller** [comment]
I'm modifying this locally for now. I'd be happy to do a PR or do it as a separate theme. I thought Inconsolata was the most legible 

```
@import url(https://fonts.googleapis.com/css?family=Inconsolata);
```

and then

```
  --hypergrid--font-size: 15px;
  --hypergrid-header--font-size: 15px;
  --hypergrid--font-family: "Inconsolata";
  --hypergrid-header--font-family: "Inconsolata";
```

**Comment by RandomFractals** [comment]
that would have to be a custom theme.

Can you attach a pic to show what you mean by equal length columns without any weird abbreviations?

Other than the font itself, I don't see how those changes would adjust columns display.

**Comment by mhkeller** [comment]
> Can you attach a pic to show what you mean by equal length columns without any weird abbreviations?

I just mean, it's often useful to spot check data that should all have, say, a three-character code, by visually scanning to see if any don't align. Here, it's easy to see that there is an extra `I` character in a monospace font.

```
three_character_id,value
AAA,10
AAAI,10
BBB,10
CCC,10
CCCI,10
```

I can put a custom theme together. I can do a monospace variation of each of the existing ones if that doesn't get too complicated.

**Comment by RandomFractals** [comment]
oh, I see. If you do create a custom monospace theme, please do both dark and light.

Light is default and dark themes just use `.dark.css` file naming convention.

**Comment by RandomFractals** [comment]
@mhkeller do you mind if we close this ticket? 

I will be updating data preview dependencies soon, and some of the above might not work with the new perspective viewer grid.

**Comment by mhkeller** [comment]
Yeah all good!
