### ISSUE TITLE
Hover style takes precedence over selected row

### ISSUE THREAD

**Issue by mhkeller** [RandomFractals/vscode-data-preview#197]
When you click a row in the hypergrid, it should take on the `--hypergrid-selection--background` color but it doesn't because the `--hypergrid-row-hover--background` and `--hypergrid-row-hover--color` styles take precedence. I can't figure out how to set up a better inheritance but I've never worked with vscode extension css before.

**Comment by RandomFractals** [comment]
that vscode css works the same as any web view. 

Those styles are just copied over from perspective library for the hyper grid display and themes.

**Comment by mhkeller** [comment]
I'm not familiar with the perspective library and hypergrid. Do you have a link? This doesn't look like standard CSS, though, since it has these custom property fields as opposed to putting styles in separate clasess.

**Comment by RandomFractals** [comment]
this is the library that provides grid and charts display for the data preview and different supported data file formats: https://github.com/finos/perspective/

feel free to log this issue in their repo and link this.

**Comment by mhkeller** [comment]
I looked into this a little bit and interestingly it doesn't seem to show a selection style although there seems to be some css in there. I'll close it since it doesn't seem like there's anything in this library that can change their CSS.
