### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mehrdad-dev** [RandomFractals/vscode-data-preview#202]
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.0.0`
- OS Version: `Linux x64 5.3.0-46-generic`
- VSCode version: `1.44.2`

[RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt](https://github.com/RandomFractals/vscode-data-preview/files/4586839/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt)

**Comment by RandomFractals** [comment]
see #173
