### ISSUE TITLE
Moving average for line charts

### ISSUE THREAD

**Issue by yohan-pg** [RandomFractals/vscode-data-preview#208]
Thanks for your tool, it's super helpful! The only feature I find myself missing is the ability to smooth out line charts with a moving average. I would love to implement it if you could give me a few pointers.

**Comment by RandomFractals** [comment]
these are the only supported aggregate functions for the provided basic charts for now:

https://github.com/RandomFractals/vscode-data-preview#supported-aggregate-functions

I am going to close this ticket & revisit it on the next update.
