### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by martinmengh** [RandomFractals/vscode-data-preview#210]
Hi.  This is a great extension I'd really like to use it to preview some XLS file.  But I am stumbled by persistent problem during installation.  Visual studio code simply responds with "failed to install datafractalsinc/data-preview"  .

I am using  Windows 7 64bit system with Visual Studio Code Version 1.30.1.

What should I do.  Thanks.

**Comment by RandomFractals** [comment]
this is most likely b/c you are trying to install it in an older vscode version that is not supported by this extension.

Data preview requires vscode v1.36.x or higher per engines setting in package.json ...

```
"engines": {
    "vscode": "^1.36.0",
```
