### ISSUE TITLE
2️⃣ Is there a digit limit? If there is, how can I increase digit limit?

### ISSUE THREAD

**Issue by yedhrab** [RandomFractals/vscode-data-preview#211]
I found that digit limit is fixed by 2. How can I change it 3 or more?

![image](https://user-images.githubusercontent.com/49655146/88094620-8c747300-cb9c-11ea-9047-4e572f1cf824.png)

**Comment by RandomFractals** [comment]
this will be worked on in fall as part of #156 enhancement.
