### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by yedhrab** [RandomFractals/vscode-data-preview#212]
- Issue Type: `Bug`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.47.3`

![image](https://user-images.githubusercontent.com/49655146/89118987-2a2c4400-d4b3-11ea-831d-3d219e4777e5.png)

**Comment by RandomFractals** [comment]
see #173
