### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yedhrab** [RandomFractals/vscode-data-preview#213]
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.47.3`

[RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt](https://github.com/RandomFractals/vscode-data-preview/files/5011858/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt)

**Comment by RandomFractals** [comment]
see #173
