### ISSUE TITLE
It does not load

### ISSUE THREAD

**Issue by hediet** [RandomFractals/vscode-data-preview#216]
This is what it looks like:
![image](https://user-images.githubusercontent.com/2931520/89523772-bc9a5380-d7e3-11ea-87f7-7a4983359095.png)

I get this message in the dev tools:
```
[Embedded Page] Refused to load the script 'vscode-resource:/c:/Users/Henning Dieterichs/.vscode/extensions/randomfractalsinc.vscode-data-preview-2.0.0/web/scripts/perspective-viewer-d3fc.js' because it violates the following Content Security Policy directive: "script-src vscode-webview-resource: blob: data: https: 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

I'm using windows 10 / VS Code 1.47.3 / Data Preview 2.0.0

**Comment by hediet** [comment]
Maybe this is due to the npm outage. You should ship perspective with your extension!

**Comment by RandomFractals** [comment]
What you are seeing is most likely related to #203 

I just tried loading some of the sample data files from this extension's ./data folder and everything looks fine.

Thank you for your suggestion!
