### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by cmdel** [RandomFractals/vscode-data-preview#219]
I've recently had an issue with the extension where it appears to be unable to "render" the UI view?
I can't see to be able to load any CSV file to view. It used to work perfectly fine.
![image](https://user-images.githubusercontent.com/222043/92242505-c634db00-eeb7-11ea-8379-21c9735e33da.png)

I've tried to disable and re-enable as well as disable and re-enable without any success.

Any ideas?

Data PReview v.2.0.0
VSCode 1.48.2

Thanks

**Comment by RandomFractals** [comment]
could be related to #203 & most recent vscode update for webviews in that release.

I'll check. Thanks for letting me know.
