### ISSUE TITLE
I am getting a crash window

### ISSUE THREAD

**Issue by ezequias** [RandomFractals/vscode-data-preview#220]
Hi

I am opening a 162Mb file and the data preview is crashing.

Could you provide me some information about it?

Is there any limitation on that?

The message is: **The window has crashed** : We are sorry for the inconvenience! You can reopen the window to continue where you left off.

**Comment by RandomFractals** [comment]
Sounds like the file you are trying to open is too large for you to preview on your machine.

Not sure what more information I can provide about it.

**Comment by ezequias** [comment]
Thank you @RandomFractals when I try a smaller it works fine. My machine has 8Gb RAM and I don't think this is a problem of memory.

**Comment by RandomFractals** [comment]
vscode has limitations for blocking data reads from disk.

I never added data streaming, so there are limits to the data files you can preview with this extension, but you should be able to do that for files around 10Mbytes per my tests. 

Try some from the /data folder in this repo.

**Comment by ezequias** [comment]
> vscode has limitations for blocking data reads from disk.
> 
> I never added data streaming, so there are limits to the data files you can preview with this extension, but you should be able to do that for files around 10Mbytes per my tests.
> 
> Try some from the /data folder in this repo.

OK, 10Mb is too little for me. I really like your extension but this limitation makes me go to another alternative.

**Comment by RandomFractals** [comment]
ok. Let me know what other alternative you find.

Thanks!

**Comment by RandomFractals** [comment]
one of the data streaming tickets I have on my todo list: #167

I am open to PRs & you can always donate to see that feature added soon! :)
