### ISSUE TITLE
VSCODE Crashes after load large file

### ISSUE THREAD

**Issue by ezequias** [RandomFractals/vscode-data-preview#221]
Issue Type: <b>Bug</b>

I am trying to open a **700k lines** csv file and it crashes every time. I can't see the log even with log_level on 'Debug'

I got the error after reopening: **An error occurred while loading view: data.preview**

If the file is a smaller (**500k lines**) the extension **works fine**.

Extension version: 2.0.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RandomFractals** [comment]
that is not true. you can try some large data files from this repo data samples:

https://github.com/RandomFractals/vscode-data-preview/tree/master/data/excel

**Comment by RandomFractals** [comment]
example of large csv loaded with similar system info:

![image](https://user-images.githubusercontent.com/656833/92534680-07e8bd00-f1fb-11ea-8433-8661343e4f0a.png)

**Comment by ezequias** [comment]
I had mentioned 700K not 42K

**Comment by RandomFractals** [comment]
see more info here: https://github.com/RandomFractals/vscode-data-preview/issues/220#issuecomment-689174263

**Comment by RandomFractals** [comment]
if you'd like to load large files, I recommend you convert your data to .arrow format:

![image](https://user-images.githubusercontent.com/656833/92535729-86465e80-f1fd-11ea-8006-6db3818152d4.png)

**Comment by RandomFractals** [comment]
also, please see this note clearly stated in my docs:

https://github.com/RandomFractals/vscode-data-preview#next-v
