### ISSUE TITLE
Error: Unexpected end of JSON input when previewing JSON, if any object contain a value with // in it

### ISSUE THREAD

**Issue by sat4star** [RandomFractals/vscode-data-preview#222]
Error: Unexpected end of JSON input when previewing JSON, if any object contain a value with // in it

Examples:
Failing JSON    =>  { "a": "b//d" }
Working JSON => { "a": "b/ /d" }

VS Code : version 1.48
Data Preview : v2.0.0

**Comment by RandomFractals** [comment]
@sat4star please provide a full .json data file you are trying & a pic of the error you get.

**Comment by RandomFractals** [comment]
confrimed. most likely releated to this regex I added to strip out comments for loading settings.json files:

```      if (dataUrl.endsWith('.json')) {
        // strip out comments from vscode settings .json :)
        const comments: RegExp = new RegExp(/\/\*[\s\S]*?\*\/|\/\/.*/g);
        content = content.replace(comments, '');
      }
```

**Comment by kartben** [comment]
I can confirm I just got bit by this one, with a JSON string containing a URL ("http:<strong>//</strong>acme.com")

**Comment by RandomFractals** [comment]
yeah, I need to patch that regex or exclude vscode settings.json from data preview since that config is not even a valid json file :)

**Comment by RandomFractals** [comment]
@kartben sorry about that. I'll try to patch this weekend.

**Comment by RandomFractals** [comment]
ok, @sat4star & @kartben I asked vscode team what they use for json and jsonc files like settings.json. 

I will be switching to node-jsonc-parser in my json data provider for loading pure json and json with comments files.

That should fix this issue and streamline json data reads a bit.

I'll try to push that update this weekend.

see: https://github.com/microsoft/node-jsonc-parser

**Comment by RandomFractals** [comment]
parsing json with jsonc-parse got this resolved.

I need to enhance flatten json for better display of nested json docs in a grid view. see #168 

quick settings.json render pic:

![data-preview-settings-json](https://user-images.githubusercontent.com/656833/94374696-9aca9800-00d3-11eb-92e4-b440e6c26d20.png)

**Comment by RandomFractals** [comment]
@sat4star this is the best I can do for invalid json display for now:

![image](https://user-images.githubusercontent.com/656833/94379897-bbf1af80-00f8-11eb-857e-d893088e85c3.png)
