### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gelrodrigues** [RandomFractals/vscode-data-preview#226]
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.1.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Gel\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment]
see #173
