### ISSUE TITLE
扩展导致 cpu 负载高

### ISSUE THREAD

**Issue by Halsey-TJ** [RandomFractals/vscode-data-preview#231]
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.2.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.49.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\翕\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment]
duplicate of #173
