### ISSUE TITLE
jsonlines reader

### ISSUE THREAD

**Issue by aborruso** [RandomFractals/vscode-data-preview#233]
Hi,
first of all thank you very much.

I love the way vscode-data-preview parse jsonl files. It would be nice in some circumstances for me to do it via command-line.
Is there some cli that I can use?

Thank you

**Comment by RandomFractals** [comment]
I have considered adding some data transform commands, but not as cli, rather as additionitional Data: Transform to {format} commands you can run from Command Palette on an open data file this extension supports.

**Comment by RandomFractals** [comment]
@aborruso have you tried jq for jsonl cli you are looking for?

https://zxvf.org/post/jq-as-grep/

**Comment by aborruso** [comment]
@RandomFractals  I use it a lot
