### ISSUE TITLE
Describe file schema

### ISSUE THREAD

**Issue by TonyGaul** [RandomFractals/vscode-data-preview#235]
What would be great is to describe the file schema i.e. field names and data types.  For example I want to load a parquet or json file into Snowflake... so... if we can open & inspect the file, then generate a simple ANSI SQL create table statement.  If too much effort, at least return field names and data types.
Plus the parquet support!
Thanks

**Comment by RandomFractals** [comment]
currently, data preview allows you to save and load data file config.

see this for example: https://github.com/RandomFractals/vscode-data-preview/blob/master/data/excel/StateCapitals.config

I'll take another look at adding parquet support soon. Last I checked all parquet JS libs required native nodejs modules & vscode doesn't support those well.

**Comment by TonyGaul** [comment]
Hi, what sort of effort / $$$ would be involved to describe the file metadata?  The ERD Editor seems to only generate schemas based on manual input, not automatically reading a file and inferring the schema.  I am struggling to find a tool to support data warehousing that can read a variety of files (json, xml, csv, parquet, avro etc) and infer a schema based on profiling the data.  I don't have a bucket load of cash, but can sponsor personally.

**Comment by RandomFractals** [comment]
it's just not something I want to get into with this extension, or have the time for. at least not this year.

You can support the work it does already via the sponsor buttons, if you like it & use it often.

& I will accept a PR if you add a generic Save as Sql option to the data preview web view. Should be fairly straightforward to implement it. See closed issues how I added other data file saves.

**Comment by TonyGaul** [comment]
OK thanks for the feedback.  I just found your solution today and am not a .net / application developer, more of a data warehouse / BI developer.  Would like to try adding functionality such as what I have asked for, but suck at this type of coding.  Thanks anyway, will continue exploring!

Btw your solution does seem nice at what it does!

**Comment by RandomFractals** [comment]
ok. Thanks!
