### ISSUE TITLE
Automatically reload files when changed

### ISSUE THREAD

**Issue by jtrakk** [RandomFractals/vscode-data-preview#241]
It would be nice to automatically reload changed files, without needing to press the button manually. Is it possible to enable that?

**Comment by RandomFractals** [comment]
currently this works for open text data documents per changes in #172 

Adding data preview reload for other file changes can be done with file watchers, but I don't plan to implement that feature at the moment.

Please use Refresh button in data preview view for binary data files reload.

**Comment by RandomFractals** [comment]
related: #278
