### ISSUE TITLE
Scroll sideways with shift-scroll

### ISSUE THREAD

**Issue by jtrakk** [RandomFractals/vscode-data-preview#242]
Many programs support horizontal scrolling when holding the Shift key. This is a nice feature for wide tables.

**Comment by RandomFractals** [comment]
I agree it would be nice to have this feature, but I don't plan to work on this any time soon.

**Comment by richc117** [comment]
@RandomFractals this would really improve usability and its a very common interaction pattern for tables.

**Comment by RandomFractals** [comment]
@richc117 I agree. Data Preview is showing its age. I have not checked if improvements were made for this UX in the latest version of Perspective viewer library I am using to show data, but you can try the new Tabular Data Viewer prototype with CSV files. Just change view Setting to Perspective: https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.tabular-data-viewer
