### ISSUE TITLE
Doesn't works on VS Code Insider for Mac M1 (without data)

### ISSUE THREAD

**Issue by yedhrab** [RandomFractals/vscode-data-preview#245]
<img width="1180" alt="Screen Shot 2021-01-06 at 22 52 10" src="https://user-images.githubusercontent.com/49655146/103813863-d16c6300-5071-11eb-8cc5-81017785fb96.png">

**Comment by RandomFractals** [comment]
I am not sure what you mean by "(without data)".

Did you open a Data Preview for some data file? How did you get a black grid view controls display? I've never seen that.

This screenshot is not enough to investigate further and I don't have Mac M1 to test it :(

**Comment by yedhrab** [comment]
Sorry for low information. When I open csv file that had data with Data Preview on VS Code Insider for MacBook M1 , nothing shows to me and shows me that picture. When I try to open that csv file on Windows VS Code, it works.

**Comment by RandomFractals** [comment]
@yedhrab data preview has a custom debug view. Have you seen any errors when you click on > link button in its toolbar?

Also, worth checking out vscode debug panel to see if it has any errors reported for this webview extension.

Not sure why that running it on macbook m1 would be an issue. The file reading api I use is basic nodejs fs.

**Comment by yedhrab** [comment]
I checked `>` button but there was no error message there. Last message is `data.view:complete!`. 

The result that VSCode Insiders dev tools console shows me is below
<img width="556" alt="Screen Shot 2021-01-09 at 12 29 26" src="https://user-images.githubusercontent.com/49655146/104088240-532cde00-5276-11eb-9dd1-934ed0039898.png">

**Comment by RandomFractals** [comment]
that's a bit more info. still not much to check why data is not loading. I'll see if my stats update methods do anything tricky. I doubt.

Have you tried loading other data files, like .xlsb, or json? Those are processed by different data providers, unlike csv which is just read as text.

**Comment by yedhrab** [comment]
First of all, `.csv` file is not blank of course

<img width="1680" alt="Screen Shot 2021-01-10 at 22 01 41" src="https://user-images.githubusercontent.com/49655146/104132596-7a2b0300-538f-11eb-8b1f-09bf82d86e2e.png">

 I just tested `.xlsb` file and result is in the below

<img width="834" alt="Screen Shot 2021-01-10 at 21 55 46" src="https://user-images.githubusercontent.com/49655146/104132513-c7f33b80-538e-11eb-9bf4-cba1845b3336.png">


> Theme: [Dark Code](https://marketplace.visualstudio.com/items?itemName=yedhrab.darkcode-theme-adopted-python-and-markdown)

**Comment by RandomFractals** [comment]
ok. so, looks like it fails in stats update. Thanks for trying it with `.xlsb`.
