### ISSUE TITLE
Productivity enhancement

### ISSUE THREAD

**Issue by jdb78** [RandomFractals/vscode-data-preview#247]
Let me first say how much I appreciate your hard work! I really love the extension!

An improvement really pushing productivity would be to allow typing a variable name with autocompletion in "Group By", "Split By", "Sort" and "Filter" instead of dragging and dropping variables. This would make things a lot faster.

Another cool bit would be a toggle switch for the visible columns and a search field. This would help particularly if there are many columns.

**Comment by RandomFractals** [comment]
@jdb78 thanks for the kind words. Happy to hear you like this extension.

As for autocompletion enhancement, it's a limitation of perspective viewer I am using and I brought it to their attention in https://github.com/finos/perspective/issues/704 

See if you want to upvote it there for perspective lib authors to take a look into it.
