### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rafia22110** [RandomFractals/vscode-data-preview#248]
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.2.0`
- OS Version: `Windows_NT ia32 10.0.18363`
- VSCode version: `1.53.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\rafia\AppData\Local\Temp\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment]
duplicate of #173
