### ISSUE TITLE
how to use the tool to view parquet files

### ISSUE THREAD

**Issue by cstmgl** [RandomFractals/vscode-data-preview#259]
Hi all,
I found this tool in the vscode market place when I search for parquet.
I checked the readme but I still don't understand how can I view a parquet file.
Is there any instructions I can follow?
This is what I see when I open a parquet file:

![image](https://user-images.githubusercontent.com/33542778/111628807-e8a59a80-87f0-11eb-95ef-7d9b94429f9a.png)
I would like obviously to see the content of the file, maybe as a json or any other kind of way but I fail to achieve that.
My file is not so big but I see that I get this in the bottom for a long time:
![image](https://user-images.githubusercontent.com/33542778/111628953-112d9480-87f1-11eb-914e-1364d91cefe6.png)

I really just don't know how to use this tool, sorry if my question is very obvious

**Comment by RandomFractals** [comment]
Parquet data files support is very alpha and has limitations of the TS library I am using to read them. 

see here for more info: https://github.com/RandomFractals/vscode-data-preview/issues/13#issuecomment-787478728
