### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by gilesagnel** [RandomFractals/vscode-data-preview#264]
- Issue Type: `Bug`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.3.0`
- OS Version: `Linux x64 4.15.0-140-generic`
- VS Code version: `1.55.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by RandomFractals** [comment]
what was the issue? closing this as there is no description provided.
