### ISSUE TITLE
[Possible bug] Data Preview does not load anything until I change the view perspective and reload the content

### ISSUE THREAD

**Issue by putopavel** [RandomFractals/vscode-data-preview#268]
Whenever I open any kind of file using this extension, the displayed dataTable seems empty (although in the logs I can see it detected records). Once I change the view perspective and reload the content, I can see the file's content displayed. Here you can see the behavior:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/9091619/115352079-3a0dc480-a1b7-11eb-81e2-77bb7cda09e5.gif)

Why is this happening? Is there something wrong with my environment?

Thanks in advance.

**Comment by RandomFractals** [comment]
not just your environment. I had multiple reports of similar issue. Try changing data preview to light UI theme and see #250

**Comment by putopavel** [comment]
You are right; I will close the issue and follow it there. Thanks for your response.
