### ISSUE TITLE
Feature request: Log-log and semi-log plots

### ISSUE THREAD

**Issue by PierreMarchand20** [RandomFractals/vscode-data-preview#280]
It would be a nice feature if we could use logarithm scales for Y line chart ([log-log](https://en.wikipedia.org/wiki/Log–log_plot) and [semi-log](https://en.wikipedia.org/wiki/Semi-log_plot) plots). I did not find a way to do it so I assumed it should be a feature request, but I may be mistaking.

**Comment by RandomFractals** [comment]
@PierreMarchand20 this sounds like a new chart type request for perspective viewer to add and support.

Please log it in the perspective viewer repo for the developers of that library to review and add: https://github.com/finos/perspective/issues

Data preview only provides a light web view wrapper around that data viewer to view different data files in vscode.
