### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by garagon** [RandomFractals/vscode-data-preview#282]
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.3.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.0`

[RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt](https://github.com/RandomFractals/vscode-data-preview/files/6794574/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt)

**Comment by RandomFractals** [comment]
duplicate of #173
