### ISSUE TITLE
Make column headers in data view drag/droppable into the filter/sort/pivots section

### ISSUE THREAD

**Issue by uditrana** [RandomFractals/vscode-data-preview#288]
Right now you can only drag and drop columns from the left side list but I (and other coworkers) often feel us trying to drag the columns directly from the data view. Right now the only thing you can do with those column labels is double click which populates the column into sort but I was wondering if we could drag and drop from there into any of the fields.

I understand this is a really minor nit/enhancement though.

**Comment by RandomFractals** [comment]
Interesting idea. However, adding drag and drop columns from table view into filters section could be very involved and require some of the perspective UI library rework. 

Feel free to post this request in their repo. I don't plan to add such enhancement to this vscode extension.

Please use side panel for your column selections.

Thanks for our feedback.
