### ISSUE TITLE
Feature Request: Add a checkbox for index/rank

### ISSUE THREAD

**Issue by uditrana** [RandomFractals/vscode-data-preview#289]
I am often using the extension to view and sort quick csvs to prepare reports for meetings but when I sort by certain columns, I don't actually have a way to get a rank of a specific row by that sort because there is no index showing on the left side of the viewer. 

Or maybe add a rank option for the functions for new column?

**Comment by RandomFractals** [comment]
@uditrana Can you provide an example?

**Comment by RandomFractals** [comment]
Closing this as I don't plan to add generated ids, rank, or superficial keys column to data preview.

If your data input already provides some keys you'd like to get data ordered by, you should be able to use them.
