### ISSUE TITLE
Data missing in some columns in JSON preview

### ISSUE THREAD

**Issue by CherryDT** [RandomFractals/vscode-data-preview#292]
See screenshot:
![image](https://user-images.githubusercontent.com/6010463/133391077-daba952c-4e36-4c75-9b73-bb0fbbb1e8c2.png)

As you can see, the `phone` and `ctecId` columns are missing their data in the preview.

This is the JSON data:

```json
[
  {
    "prontoId": 0,
    "email": "aaa@aaa.com"
  },
  {
    "prontoId": 1,
    "email": "bbb@bbb.com"
  },
  {
    "prontoId": 2,
    "email": "ccc@ccc.com",
    "phone": "1234567890",
    "ctecId": "A123456"
  },
  {
    "prontoId": 3,
    "email": "ddd@ddd.com",
    "phone": "0987654321",
    "ctecId": "A654321"
  },
  {
    "prontoId": 4,
    "email": "eee@eee.com"
  },
  {
    "prontoId": 5,
    "email": "fff@fff.com",
    "phone": "1112223333"
  }
]
```

**Comment by RandomFractals** [comment]
This is related to #238 and is because your first two data entries in that json array doesn't have phone or ctecId properties.

if you add blanks there, it should work. Data preview doesn't scan random rows or first 10 or 100 rows to infer table columns yet. Columns are determined by the first record in your dataset and it's important that you have all the properties and correct types in your first record.

**Comment by CherryDT** [comment]
Hm, what you say doesn't make sense though, because the columns _are_ displayed... just empty.

**Comment by RandomFractals** [comment]
ok. I'll take another look and will keep this open for now. thanks!

**Comment by CherryDT** [comment]
Yes it works then.

But what I mean is this: If the columns are based on what's in the first record, then why are `phone` and `ctecId` displayed as columns nonetheless? Even more interestingly, it seems like there are even types deferred somehow, because `phone` is shown as number type on the left sidebar...

**Comment by RandomFractals** [comment]
that is the current limitation and since I'll be updating some of the dependencies of this extension soon, I don't think it's worthwhile to dig in deeper here. 

So, I am going to close this for now. Just make sure all your records have the property fields you'd like to view and filter.

**Comment by lyons-g** [comment]
Hi, when you say you'll be updating some of the dependencies soon, will this limitation be addressed?

**Comment by RandomFractals** [comment]
> Hi, when you say you'll be updating some of the dependencies soon, will this limitation be addressed?

yes. I am currently working on new duckdb tools, and plan to get back to data preview in March/April.

**Comment by lyons-g** [comment]
> > Hi, when you say you'll be updating some of the dependencies soon, will this limitation be addressed?
> 
> yes. I am currently working on new duckdb tools, and plan to get back to data preview in March/April.

Great - thanks for the reply
