### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pietrodantuono** [RandomFractals/vscode-data-preview#294]
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.3.0`
- OS Version: `Windows_NT x64 10.0.22478`
- VS Code version: `1.62.0-insider`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt](https://github.com/RandomFractals/vscode-data-preview/files/7379289/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt)

**Comment by RandomFractals** [comment]
duplicated of #173
