### ISSUE TITLE
Need x/y line plot or smaller markers on x/y scatter plot

### ISSUE THREAD

**Issue by oscarrutt** [RandomFractals/vscode-data-preview#299]
When making an x/y scatter plot, the markers are so large that they obscure the details of the plot when there are more than probably a couple hundred points. Either (1) please make the marker size adjustable, or preferably (2) please add a x/y line plot.

**Comment by RandomFractals** [comment]
@oscarrutt Can you provide a screenshot and a link to a sample public dataset for this use case?

**Comment by RandomFractals** [comment]
@oscarrutt sounds like this is chart specific issue. Please log it in the perspective viewer repo for the developers of that library to review and fix: https://github.com/finos/perspective/issues

Data preview only provides a light webivew wrapper around that data viewer to view different data files in vscode.
