### ISSUE TITLE
Tooltip covers up the cursor position when exploring data in a graph

### ISSUE THREAD

**Issue by oscarrutt** [RandomFractals/vscode-data-preview#300]
In some plots, the tooltip that shows the x and y data values nearest the cursor should be offset so that the tip of the cursor is visible. As it is, the tooltip obscures the actual location of the cursor and you can't tell exactly what graphical point corresponds to the textual information in the tooltip.

**Comment by RandomFractals** [comment]
@oscarrutt as I mentioned in #299, please provide screenshots for your issues.

Also, this might be a request for the Perspective JS library and charts Data Preview uses for the data views in vscode:

https://github.com/finos/perspective/

**Comment by RandomFractals** [comment]
@oscarrutt I am going to close this issue. Please log it in the viewer library I linked to above for perspective viewer devs to review and fix.
