### ISSUE TITLE
Add option to hide Preview Data context menu options to ignore some files based on file extensions

### ISSUE THREAD

**Issue by PePoDev** [RandomFractals/vscode-data-preview#301]
This extension is awesome!

But I don't want to open the README file automatically with this extension

I think It cloud be better if this extension has an option to add a list of file extensions to ignore and open with the editor by default.

**Comment by RandomFractals** [comment]
Good point. I might add some excludes later, especially for the standard .md files like README.md and `.config` files others mentioned before.

**Comment by Unitedfront68** [comment]
#279
