### ISSUE TITLE
Can't change data type in view

### ISSUE THREAD

**Issue by catatwork217** [RandomFractals/vscode-data-preview#302]
Is there a way to modify the data type for a particular column after importing data into Data Preview? For example I can see the data source, columns and row descriptions in source in Data Console Log or any of the views, but there doesn't seem to be any option to modify / update a data type from Text to Number or vice-versa. See screenshots below. 
![image](https://user-images.githubusercontent.com/80551966/156784667-aaba1203-9c5d-45bc-af82-3f10d32e0561.png)

**Comment by RandomFractals** [comment]
@catatwork217 currently that's not possible in data preview. You can try new Tabular data viewer extension which uses the latest version of perspective viewer JS and lets you change precision for numeric data.

https://github.com/RandomFractals/tabular-data-viewer
