### ISSUE TITLE
Wsl

### ISSUE THREAD

**Issue by aytkn7** [RandomFractals/vscode-data-preview#304]
When working in windows 10 with wsl ubuntu, the extension can't preview data. (extension url for which I use for connecting wsl from windows https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)

**Comment by RandomFractals** [comment]
Currently, there are no plans to add WSL support in the free old version of Data Preview.

I am working on a Pro version of this extension for sponsors-only and will consider providing that feature to users supporting those dev efforts.

**Comment by fwindolf** [comment]
Sorry for opening a closed issue.

Would you be willing to accept a PR for this feature for the free old version @RandomFractals?
