### ISSUE TITLE
What happened to randomfractalsinc.snippets-viewer

### ISSUE THREAD

**Issue by lonix1** [RandomFractals/vscode-data-preview#305]
@RandomFractals What happened to "randomfractalsinc.snippets-viewer" extension? It disappeared from github and the marketplace without warning. It was really useful.

**Comment by RandomFractals** [comment]
I removed it from vscode marketplace & unpublished it along with many other extensions I've built for code IDE since I don't plan to improve or maintain them moving forward. More info here: 

https://twitter.com/TarasNovak/status/1520050964509691905

**Comment by lonix1** [comment]
Thanks for the reply. You could have left them though, maybe someone could have improved on them?

I read the tweet - I'm sorry it didn't work out. I think your extensions were very good!

**Comment by RandomFractals** [comment]
@lonix1 I can grant you access to that private repo, if you become a sponsor, and would like to continue using that extension, or grab a `.vsix` to install.

**Comment by lonix1** [comment]
I know nothing of vs extensions, I wouldn't know what to do with it! :yum: But it's a nice offer.
It's a pity there's no monetisation feature for vs extensions - like "apps". Then extensions authors like you could make a full job of it. I see everything on the "marketplace" is really OSS (And people ripping off others' work, changing the name and logo, and passing it off as their own. It's becoming just as bad as npm).

**Comment by RandomFractals** [comment]
@lonix1 our Snippets Viewer extension is public again with new GPL-3.0 license and new sponsoring links and buttons I would suggest you use to sponsor that extension development and maintenance releases, especially if you use it at work. See this tweet for updates: https://twitter.com/TarasNovak/status/1564254155702779906
