### ISSUE TITLE
macos 12.1  还原视图时出错: data.preview

### ISSUE THREAD

**Issue by youngxinler** [RandomFractals/vscode-data-preview#308]
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/36697727/187011916-4e634335-e94a-4ac5-bb6b-22786add5533.png">

**Comment by RandomFractals** [comment]
@youngxinler that might be the case. However, your ticket has very little details and parquet files loading in this extension is very limited, i.e. it doesn't load compressed parquet files. So, I am going to close this issue.
