### ISSUE TITLE
Update to latest finos/perspective?

### ISSUE THREAD

**Issue by mhkeller** [RandomFractals/vscode-data-preview#319]
Will this plugin be updated to use the latest finos/perspective version? It's still such a useful plugin!

**Comment by RandomFractals** [comment]
Most likely it will be updated next year. I did not get to it this year.

Meanwhile, I'd recommend you try new Tabular Data Viewer alpha v. with more recent Perspective view integration and CSV data loading:

https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.tabular-data-viewer
