### ISSUE TITLE
为啥临时文件用不了

### ISSUE THREAD

**Issue by izilongwan** [RandomFractals/vscode-data-preview#327]
Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/48234072/223901961-445497df-3987-425e-be27-c0aadeab1b95.png)
![image](https://user-images.githubusercontent.com/48234072/223902101-fb009c0d-939b-4cda-9cf7-529977440786.png)

![image](https://user-images.githubusercontent.com/48234072/223902194-e654d663-59b3-481b-8157-d8ab5890a4cd.png)

需要增加全选/反选按钮
Extension version: 2.3.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (15.86GB free)|
|Process Argv|-n --enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id f24fe983-78b2-424b-b832-a858c79abae1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30662444

```

</details>

**Comment by RandomFractals** [comment]
@izilongwan Temporary files are not supported by this extension, only local data files and some remote data endpoints over https://

There are currently no plans to add virtual documents support in this extension. They are handled differently in vscode.

Just save the data file you'd like to preview.
