### ISSUE TITLE
data preview cannot be found in vscode marketplace

### ISSUE THREAD

**Issue by Kou-99** [RandomFractals/vscode-data-preview#331]
Hi, thanks for your great work! I have been using data preview for a while. But today I found that data preview cannot be found in vscode marketplace and the link https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview point to a 404 page. What happened?
![Snipaste_2023-03-25_16-35-31](https://user-images.githubusercontent.com/32770847/227706668-b827272a-eeaf-4c28-a76e-e7534b326bba.png)

**Comment by RandomFractals** [comment]
Data Preview is showing its age, and I've decided to unpublish it from VSCode marketplace.

I plan to release a Pro version of this extension in a month or so. You can sponsor our dev work on that extension and other data oriented pro tools to get notified about new extensions and updates we'll be releasing in the next few weeks:

https://github.com/sponsors/RandomFractals/sponsorships?sponsor=RandomFractals&tier_id=18884

**Comment by RandomFractals** [comment]
It's back in marketplace now. I would strongly suggest you use Tabular Data Viewer or other more up to date data viewers instead.
