### ISSUE TITLE
It is not clear how to save changes to file.

### ISSUE THREAD

**Issue by ormach** [RandomFractals/vscode-data-preview#341]
I have a JSON file, that I want to edit and preview as a table. After I make changes to a particular cell, there is no clear way to save these changes.

There is a drop down list in the top right corner with the 'Save' label, but I can't figure out how it works. Checked docks, but couldn't find anything related to saving changes.

I was wondering if there is a save button or a shortcut to save changes?

**Comment by BasilaryGroup** [comment]
Works for me. But I have only viewed small jsonl files, less than a 200 lines.

1. click on Save selector
2. select the output format
3. wait....and wait.....it is busy and I don't see any progress feedback
4. a "Save As" dialog will eventually appear so you can save the output

Did you try to click the ">" button, left side of the toolbar, to show the View Data Console Log? Was there an error message?
